### PR TITLE
Fixed the incorrect exports and types in package.json

### LINKED ISSUE #335: Error about import after updating from v3.0.0 to v3.0.1
After updating from v3.0.0 to v3.0.1, I'm getting the following error:

```ts
src/create-show-and-tell-report.tsx:21:46: ERROR: Could not resolve "@sota1235/notion-sdk-js-helper"
    at failureErrorWithLog (/Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:1477:15)
    at /Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:946:25
    at runOnEndCallbacks (/Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:1317:45)
    at buildResponseToResult (/Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:944:7)
    at /Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:971:16
    at responseCallbacks.<computed> (/Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:623:9)
    at handleIncomingPacket (/Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:678:12)
    at Socket.readFromStdout (/Users/pclaerhout/Documents/Contractify/raycast-extensions/contractify-jira/node_modules/esbuild/lib/main.js:601:7)
    at Socket.emit (node:events:507:28)
    at addChunk (node:internal/streams/readable:559:12)
```

The line it complains about is this:

```
import { BlockObjects, RichTextObjects } from "@sota1235/notion-sdk-js-helper";
```

Any idea what can be causing this and how it can be fixed?

### PR DESCRIPTION
**Pull request by pieterclaerhout**
Fixes #335

From what I can see, these entries should always start with `./` as explained [here](https://webpack.js.org/guides/package-exports/)

### CODE REVIEW

**Review by sota1235 — APPROVED** [review]
thank you so much!
